---
title: "Basic structural model"
author: "Jean Palate"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{"Basic structural model"}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
suppressPackageStartupMessages(library(rjd3sts))
```


### BSM without regression variables

```{r, fig.show='hold'}
s<-retail$FurnitureStores
models<-c("Trigonometric", "HarrisonStevens", "Crude", "Dummy", "Fixed")
all<-lapply(models, function(z){sts(log(s), seasonal = z)})

a<-all[[2]]
level<-a$decomposition$level$data
elevel<-a$decomposition$level$stde
plot(level, type='l')
lines(level+2*elevel, col='red')
lines(level-2*elevel, col='red')

seas<-a$decomposition$seasonal$data
plot(seas, type='l')

rslt<-data.frame(
  Level=sapply(all, function(z){z$estimation$parameters$val[1]}),
  Slope=sapply(all, function(z){z$estimation$parameters$val[2]}),
  Seasonal=sapply(all, function(z){z$estimation$parameters$val[3]}),
  Noise=sapply(all, function(z){z$estimation$parameters$val[4]}),
  LL=sapply(all, function(z){z$estimation$likelihood$ll}),
  AIC=sapply(all, function(z){z$estimation$likelihood$aic}),
  row.names = models)

knitr::kable(rslt)

```

### BSM with pre-specified trading days effects


Diffuse regression variables should be avoided if we want to compare the models

```{r}
s<-log(retail$RetailSalesTotal)

models<-list(NULL, c(1,1,1,1,1,0,0), c(1,1,1,1,1,2,0), c(1,1,1,1,2,3,0), c(1,1,1,2,3,4,0), c(1,1,1,2,3,1,0), c(1,2,3,4,5,6,0))
cmodels<-c("none", "week days", "2-vars", "3-vars", "4-vars", "3-vars-bis", "trading days")
all<-lapply(models, function(z){sts(s, seasonal = "Crude", X.td = z, diffuse.regs = F)})


rslt<-data.frame(
  LL=sapply(all, function(z){z$estimation$likelihood$ll}),
  AIC=sapply(all, function(z){z$estimation$likelihood$aic}),
  row.names = cmodels)


knitr::kable(rslt)

knitr::knit_print(all[[5]])


# Computing calendar effects

sel<-all[[5]]

cal<-sel$estimation$X%*%sel$estimation$b
plot(cal, type='l')

# Complete seasonal component
seas<-sel$decomposition$seasonal$data+cal

# Seasonally adjusted series (in logs)
sa<-s-seas
plot(s, type='l', col="gray")
lines(sa, col="blue")

```

### Full BSM processing (with pre-specified trading days effects and outliers detection)

This algorithm is a very simplified and non optimized version of a fully automated processing

```{r}
s<-log(retail$UsedCarDealers)

# Use/choose the TD you want. Automatic selection based on AIC could be considered (see above)
o<-sts.outliers(s, X.td = c(1,1,1,2,3,1,0), seasonal = "HarrisonStevens", ls=T, ao=T, so=F)
xo<-o$model$X
xnames<-o$model$variables

# recompute the full model to get the decomposition

rslt<-sts(s, X=xo, seasonal = "HarrisonStevens")
regs<-NULL
iseas<-c(grep("x-", xnames), grep("SO", xnames))
if (length(iseas)==1){
  regs<-rslt$estimation$X[,iseas]*rslt$estimation$b[iseas]
}else if (length(iseas)>0){
  regs<-rslt$estimation$X[,iseas]%*%rslt$estimation$b[iseas]
}


regt<-NULL
itrend<-grep("LS", xnames)
if (length(itrend)==1){
  regt<-rslt$estimation$X[,itrend]*rslt$estimation$b[itrend]
}else if (length(itrend)>0){
  regt<-rslt$estimation$X[,itrend]%*%rslt$estimation$b[itrend]
}

regi<-NULL
iirr<-grep("AO", xnames)
if (length(iirr)==1) {
  regi<-rslt$estimation$X[,iirr]*rslt$estimation$b[iirr]
}else if (length(iirr)>0) {
  regi<-rslt$estimation$X[,iirr]%*%rslt$estimation$b[iirr]
}
# Complete seasonal component
seas<-rslt$decomposition$seasonal$data
if (! is.null(regs)){
  seas<-seas+regs
}

trend<-ts(rslt$decomposition$level$data, frequency = frequency(s), start=start(s))
if (! is.null(regt)){
  trend<-trend+regt
}

if (is.null(sel$decomposition$noise)){
  irr<-regi
}else{
  irr<-rslt$decomposition$noise$data
  if (! is.null(regi)){
    irr<-irr+regi
  }
}
irr<-ts(irr, frequency = frequency(s), start=start(s))
  
# Seasonally adjusted series (in logs)

sa<-s-seas
plot(s, type='l', col="gray")
lines(sa, col="blue")
lines(trend, col="red")

```